### ISSUE TITLE
decode need support all base64 Encoding types

### ISSUE THREAD

**Issue by aireet** [exts/ArtifactDeckCodeGo#2]
thanks for your open source 

when I use this lib to decode this code 

(https://www.playartifact.com/d/ADCJUQYL7kCQYsNCbhdgXfdAUqrAVqfpQNIRI9oARFUDVtBXSBTdHJpZmVDcm8gLSBVRyBDb21ibw)

it calls an illegal base64 data at input error, then I change the encode type as 'RawStdEncoding' and it worked.

so i think it's better to support 4 types (StdEncoding, RawStdEncoding, URLEncoding, RawURLEncoding) of golang base64 Encoding types

**Comment by exts** [comment]
thanks, will check this today

**Comment by exts** [comment]
So I was testing and I believe you received the wrong deck code after doing some research on the deck [found here](https://www.iyingdi.com/web/article/home/65232) it was missing the '__' which is a base64 padding character. Despite it being possible I'm going to leave it up to the developer to check if they want to handle base64 codes with or without padding characters.
